Using Zenoh's Shared Memory Buffer
eclipse-zenoh/zenoh-flow pull request #151
Opened 2023-03-20 14:57 UTC by gabrik

Using a Shared Memory buffer allows for zero-copy communication when Zenoh-Flow runtimes are running inside the same host.

---
More information to come.

2023-03-29 10:27 UTC, gabrik commented
Depends on: https://github.com/eclipse-zenoh/zenoh-flow/pull/152

2023-03-29 11:34 UTC, J-Loudet requested changes
Minor changes / refactoring, overall LGTM

2023-03-29 11:34 UTC, J-Loudet commented on zenoh-flow/src/runtime/dataflow/instance/builtin/zenoh.rs
> +                    .unwrap_or(*context.shared_memory_backoff());
We can refactor this with a closure (I'm not sure it's a 100% correct Rust code):

```rust
let get_or_default = |configuration, key, default| {
    if let Some(value) = configuration.get(key) {
        if let Ok(value) = value.as_u64() {
            return value;
        }
        log::warn!("Failed to parse / interpret provided value for {key} into u64, using default value: {default}");
    }

    default
};

let shm_elem_size = get_or_default(configuration, KEY_SHM_ELEM_SIZE, context.shared_memory_element_size() as u64) as usize;
let shm_elem_count = get_or_default(configuration, KEY_SHM_TOTAL_ELEMENTS, context.shared_memory_elements() as u64) as usize;
// etc…
```

2023-03-29 11:37 UTC, gabrik commented on zenoh-flow/src/types/context.rs
We may add other information like the `NodeId` to the `Context` and that is not per instance but per node.

2023-03-29 13:43 UTC, gabrik commented on zenoh-flow/src/runtime/dataflow/instance/runners/connector.rs
> +                            "[ZenohSender: {}] Unable to serialize into shared memory: {}",
I think the error already gives that information, but I'll add it

2023-04-03 06:58 UTC, J-Loudet approved these changes

2023-04-03 06:58 UTC, J-Loudet commented on zenoh-flow/src/runtime/dataflow/instance/builtin/zenoh.rs
> +                    log::warn!("[ZenohSink] Sending data via network, has we are unable to send it over shared memory, the serialized size is {} while shared memory is {}", data_len, self.shm_element
```suggestion
                    log::warn!("[ZenohSink] Sending data via network as we are unable to send it over shared memory, the serialized size is {} while shared memory is {}", data_len, self.shm_element_size);
```

2023-04-03 07:58 UTC, merged