test: add test script
eclipse-zenoh/zenoh-flow pull request #169
Opened 2023-10-10 15:54 UTC by PhilipTamb

This pull request wants to add the possibility to test a specific Zenoh-Flow configuration using a script

2023-10-17 16:15 UTC, gabrik requested changes
When printing use the formatter with `print(f'Some thing: {variable_name}')`
https://docs.python.org/3/tutorial/inputoutput.html#tut-f-strings

2023-10-17 16:15 UTC, gabrik commented on manual-tests/README.md
> +pip install psutil
Why not create a `requirements.txt` and install it with pip?
`pip3 install -r requirements.txt`

Also the version of the dependencies should be explicit, for reproducibility.

2023-10-17 16:15 UTC, gabrik commented on manual-tests/automated-test.py
> +        self.zenohd_path = "none"
use `None` instead of the string.

2023-10-17 16:15 UTC, gabrik commented on manual-tests/automated-test.py
> +  print(libzenoh_plugin_path[0])
use `print(f'Path of plugin library: {libzenoh_plugin_path[0]'}`

2023-10-17 16:15 UTC, gabrik commented on manual-tests/automated-test.py
> +print("[info] Launching Zenod process:  ", zf_command['zenohd_cmd'])
use `print(f'.....')`

2023-10-23 09:00 UTC, J-Loudet requested changes
Solid basis. Needs adjustments.

2023-10-23 09:00 UTC, J-Loudet commented on manual-tests/automated-test.py
> +    help="Specifies a different directory for Zenoh-Flow artifacts (default=debug)",
Shouldn't the default be "debug"?

2023-10-23 09:00 UTC, J-Loudet commented on manual-tests/automated-test.py
> +    zf_conf.zf_plugin_path = args.plugin
It is better to put the correct path in the default options. If users run the "help" option and see `"/.config/…"` they can assume that something is wrong.

There is the function: `os.path.expanduser()`.

What I suggest you do: provide a default option with `~` in the path & call `expanduser` in all cases (be it the default option or provided by the user).

2023-10-23 09:00 UTC, J-Loudet commented on manual-tests/automated-test.py
> +print("[Info] Looking for Zenohd process...")
Given that you are not just looking for `zenohd` processes, I would rather write:
```suggestion
print("[Info] Killing extra `zenohd` processes...")
```

2023-10-23 09:00 UTC, J-Loudet commented on manual-tests/automated-test.py
> +        os.kill(pid, signal.SIGKILL)
Couldn't this be simplified like so?
```suggestion
        print(f"[Info] kill process: {process.pid}")
        process.kill()
```

2023-10-23 09:00 UTC, J-Loudet commented on manual-tests/automated-test.py
> +        print("[Error] Test Zenoh-Flow configuration nodesSome nodes:  FAILED.")
Considering the previous change I asked you to do, these lines need to be removed as well.

2024-02-07 10:19 UTC, closed without merging