feat: local deadlines for Operator nodes
eclipse-zenoh/zenoh-flow pull request #47
Opened 2021-11-04 16:27 UTC by J-Loudet

This PR introduces the possibility to add local deadlines for the `run` method of Operator type nodes.

The deadline declaration is:
```yaml
deadline:
  duration: 500
  unit: ms
```

The deadline is simply _checked_ but not enforced: the `run` method of the Operator will execute until completion and, once over, we check if the time it took to execute is superior to the declared deadline.

The information is available in the `output_rule` in the form of a boolean:
```rust
    fn output_rule(
        &self,
        context: &mut Context,
        state: &mut State,
        outputs: HashMap<PortId, Data>,
        deadline_miss: bool,
    ) -> ZFResult<HashMap<PortId, NodeOutput>>;
```

This PR introduces a breaking change.

2021-11-04 16:29 UTC, J-Loudet commented on zenoh-flow/tests/local_deadline.rs
> +        Some(Duration::from_millis(500)),
This is where the deadline is declared.

2021-11-04 16:29 UTC, J-Loudet commented on zenoh-flow/tests/local_deadline.rs
> +        assert!(deadline_miss, "Expected `deadline_miss` to be: true");
We check here that the `deadline_miss` in indeed set to `true`

2021-11-05 08:36 UTC, gabrik requested changes

2021-11-05 08:48 UTC, gabrik approved these changes
All good!

2021-11-05 09:49 UTC, merged