Implementation of Logging and Replay features
eclipse-zenoh/zenoh-flow pull request #54
Opened 2021-11-17 15:38 UTC by gabrik

This PR contains the implementation of Logging and Replay features for dataflow sources.

2021-11-17 15:39 UTC, gabrik commented
@J-Loudet do you think this PR should also include the way to activate logging and replay from `zenoh-flow-ctl` and therefore updates to `zenoh-flow-daemon`?

2021-11-18 10:16 UTC, J-Loudet requested changes

2021-11-18 10:16 UTC, J-Loudet commented on zenoh-flow/src/runtime/message.rs
>      Watermark,
As discussed, we can comment them out and indicate that they are not yet defined

2021-11-18 10:16 UTC, J-Loudet commented on zenoh-flow/src/runtime/dataflow/instance/runners/mod.rs
> +    pub async fn start(&self) -> ZFResult<RunnerManager> {
As discussed, the `async` should be removed

2021-11-18 11:11 UTC, gabrik commented on zenoh-flow/src/runtime/dataflow/instance/runners/replay.rs
> +        let mut last_ts = self.context.runtime.hlc.new_timestamp();
Unfortunately it is not possible because the compiler then argues that later in the match the variable could be not initialized.

2021-11-18 12:29 UTC, J-Loudet requested changes

2021-11-18 12:29 UTC, J-Loudet commented on zenoh-flow/src/runtime/dataflow/instance/runners/connector.rs
> +    async fn take_input_links(&self) -> HashMap<PortId, LinkReceiver<Message>> {
As discussed, we should transform `self.link` and make it a `Mutex<Option<…>` to actually "take" it

2021-11-18 12:29 UTC, J-Loudet commented on zenoh-flow/src/runtime/dataflow/instance/runners/sink.rs
> +    async fn take_input_links(&self) -> HashMap<PortId, LinkReceiver<Message>> {
As discussed, we should transform `self.link` and make it a `Mutex<Option<…>` to actually "take" it

2021-11-18 13:20 UTC, J-Loudet approved these changes

2021-11-18 13:42 UTC, merged