Removing task::spawn_blocking and task::block_on, using async closures, fixes #81
eclipse-zenoh/zenoh-flow pull request #82
Opened 2022-02-16 15:12 UTC by gabrik

This PR fixes #81.

Now `NodeRunner::run_stopplable` is async, it uses async closures, and `NodeRunner::start` uses `task::spawn` instead of `task::spawn_blocking`.

Signed-off-by: gabrik <gabriele.baldoni@gmail.com>

2022-02-16 15:23 UTC, gabrik commented
Bumping also `async_std` version to 1.10 because of zenoh.

2022-02-16 16:16 UTC, J-Loudet requested changes

2022-02-16 16:16 UTC, J-Loudet commented on zenoh-flow/src/runtime/dataflow/instance/runners/mod.rs
> +        // self.stopper.trigger();
To remove ;)

2022-02-16 16:16 UTC, J-Loudet commented on zenoh-flow/src/runtime/dataflow/instance/runners/mod.rs
> +        let signal = Arc::new(Barrier::new(2));
We should explain the logic behind this barrier (in particular why the magic number 2)

2022-02-17 08:29 UTC, J-Loudet approved these changes
LGTM!

2022-02-17 08:29 UTC, merged